# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_asyncreader_wrappers", use_symbols = TRUE, package_name = "asyncreader")

#' @docType package
#' @usage NULL
#' @useDynLib asyncreader, .registration = TRUE
NULL

AsyncReadTask <- new.env(parent = emptyenv())

AsyncReadTask$new <- function(file_path) .Call(wrap__AsyncReadTask__new, file_path)

AsyncReadTask$run <- function() invisible(.Call(wrap__AsyncReadTask__run, self))

AsyncReadTask$value <- function() .Call(wrap__AsyncReadTask__value, self)

AsyncReadTask$state <- function() .Call(wrap__AsyncReadTask__state, self)

#' @export
`$.AsyncReadTask` <- function (self, name) { func <- AsyncReadTask[[name]]; environment(func) <- environment(); func }

#' @export
`[[.AsyncReadTask` <- `$.AsyncReadTask`


# nolint end
